// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/whoami.ts
import { createClient } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in NoParrot user's basic profile (id, username, full name).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const userId = ctx.getUserId();
    const { data, error } = await supabase.from("profiles").select("id, username, full_name, bio").eq("id", userId).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const profile = data ?? { id: userId, username: null, full_name: null, bio: null };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: { profile }
    };
  }
});

// src/lib/mcp/tools/list-my-recent-posts.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
var list_my_recent_posts_default = defineTool2({
  name: "list_my_recent_posts",
  title: "List my recent posts",
  description: "List the signed-in user's most recent NoParrot posts (id, title, content preview, created_at).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("How many posts to return (1-50, default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("posts").select("id, title, content, created_at, post_type").eq("user_id", ctx.getUserId()).is("deleted_at", null).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const posts = (data ?? []).map((p) => ({
      id: p.id,
      title: p.title,
      preview: p.content ? String(p.content).slice(0, 200) : null,
      post_type: p.post_type,
      created_at: p.created_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(posts, null, 2) }],
      structuredContent: { posts }
    };
  }
});

// src/lib/mcp/tools/list-my-notifications.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_my_notifications_default = defineTool3({
  name: "list_my_notifications",
  title: "List my notifications",
  description: "List the signed-in user's recent NoParrot notifications (id, type, message, read status, created_at).",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("How many notifications to return (1-50, default 20)."),
    unread_only: z2.boolean().optional().describe("If true, only return unread notifications.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, unread_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    let query = supabase.from("notifications").select("id, type, message, read, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (unread_only) query = query.eq("read", false);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const notifications = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(notifications, null, 2) }],
      structuredContent: { notifications }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nwmpstvoutkjshhhtmrk";
var mcp_default = defineMcp({
  name: "noparrot-mcp",
  title: "NoParrot",
  version: "0.1.0",
  instructions: "Tools for NoParrot, a cognitive social platform. Use `whoami` to identify the signed-in user, `list_my_recent_posts` to fetch their recent posts, and `list_my_notifications` to check their notifications. All tools respect the user's row-level security and only return the caller's own data.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_my_recent_posts_default, list_my_notifications_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
